### ISSUE TITLE
WAV is too large. Is there any other type supported?

### ISSUE THREAD

**Issue by rescue1155** [addpipe/simple-recorderjs-demo#5]
one minute of audio goes to 5MB, How can we reduce it ?

Is there any way to reduce the size before sending to server ?

**Comment by octavn** [comment]
.wav is inherently large because it contains uncompressed audio that is just raw numbers. 44100 numbers per second, each number as _big_ as 2 to the power of 16. 

If you need smaller audio files you need to take a look at solutions that compress the audio. Here are a few I've looked at in detail:
* [Using WebAudioRecorder.js to Record MP3, Vorbis and WAV Audio on Your Website](https://blog.addpipe.com/using-webaudiorecorder-js-to-record-audio-on-your-website/)
* [Recording mp3 audio in HTML5 using vmsg - a WebAssembly library based on LAME](https://blog.addpipe.com/recording-mp3-audio-in-html5-using-vmsg-a-webassembly-library-based-on-lame/)
* [Recording audio in the browser using the MediaStream Recorder API](https://blog.addpipe.com/recording-audio-in-the-browser-using-pure-html5-and-minimal-javascript/)

PS: You can use [this calculator](https://www.colincrawley.com/audio-file-size-calculator/) to accurately calculate how much a wav file will occupy given the length, sample rate, number of channels and bitrate.
